### PR TITLE
Python 3 & setuptools support

### PR DESCRIPTION
**Pull request by tgamauf**
I have updated the code so it supports Python 2 & 3 and also Setuptools instead of Distutils. I also optimized the code, which basically amounted to a full rewrite of the tool.

Would be nice to see it merged into your project and then published to pip - everything that is necessary should already be contained in this update.

### CODE REVIEW

**Comment by roy-van-de-korput** [comment]
Nice work!

When I use the suggested settings in Pycharm I get an error. Which is related to passing the --virtualenv variable

> '.' is not recognized as an internal or external command, operable program or batch file.

`C:\Users\me\AppData\Local\Programs\Python\Python36-32\Scripts\pylint-pycharm.exe --virtualenv=C:\projects\MyProject\venv\Scripts C:\projects\MyProject\my_script.py `

**Comment by tgamauf** [comment]
Thank you!

I didn't consider Windows during development, and obviously activation of a virtual environment works different there - there is no "source" command (which can be shortcut by using "."). I'll look into it and try to find a solution for venvs on Windows.

**Comment by tgamauf** [comment]
I fixed the tool, it should work with Python virtualenvs on Windows now as well.
In my environment a warning is shown: "Parameterformat falsch - 65001" --> "Invalid parameter format - 65001" or something alike; this is caused by the "activate" command of the virtualenv, not the tool.

Hope this works for you!

**Comment by perses76** [comment]
Hi Thomas,

Thank you for your code. It looks great!!!
Unfortunately (or fortunately), I dont use Pycharm last 4-5 years and don't have chance to test or see your code.
Would you be interested in to join this project as and get rights to push code yourself?

Regards,

Vadim.

**Comment by tgamauf** [comment]
Hi Vadim,

I'd be happy to join the project!

Regards,
Thomas

**Comment by perses76** [comment]
Welcome aboard :)
You should get  invitation from GitHub.

**Pull request merged**
